### ISSUE TITLE
Debugging Error

### ISSUE THREAD

**Issue by aksoybekir** [rmtheis/yandex-translator-java-api#5]
Everytime I tried to translate I get this error 
The error I get is this

"Exception in thread "main" java.lang.ExceptionInInitializerError
	at run.test.main(test.java:10)
Caused by: java.lang.NullPointerException
	at com.rmtheis.yandtran.language.Language.<clinit>(Language.java:27)"

**Comment by rmtheis** [comment]
Hmm, looks like this was introduced with the changes to set a default language in #3/#4.

**Comment by rmtheis** [comment]
I reverted the changes that led to the NullPointerException. Please reopen this issue if that doesn't fix this issue for you.
