### ISSUE TITLE
how to use this library ?

### ISSUE THREAD

**Issue by TechnologyMaster** [rmtheis/yandex-translator-java-api#6]
I don't know how to use this library or to compile this project in to my gradle file. If anyone knows that plz replay me.

**Comment by DoguD** [comment]
In Android Studio you can use it by following these steps:
1- Open project view
2- Right click on app and click **New > Directory**, name it **libs**
![screen shot 2017-06-30 at 20 50 38](https://user-images.githubusercontent.com/20525079/27748025-6ae61126-5dd6-11e7-9d03-36124ab234a5.png)

3- Move the library file (.jar) to libs
4- Right click .jar file and select **Add as library**
