### ISSUE TITLE
Cannot access ApiKeys.YANDEX_API_KEY

### ISSUE THREAD

**Issue by DoguD** [rmtheis/yandex-translator-java-api#7]
In Translate.java and Detect.java, Android Studio gives an error on line `Translate.setKey(ApiKeys.YANDEX_API_KEY);` 
In order to solve it, first I made the protected YANDEX_API_KEY in ApiKeys.java public. But because of security concerns, I reverted it, and then moved **Translate.java** and **Detect.java** out of their packages (translate and detect respectively) by using Refractor.
Is there any other solution to the problem?

**Comment by rmtheis** [comment]
You can just directly paste in a string with your API key (for example, `Translate.setKey("12345");`) before you call `Translate.execute()` like the example in the Readme.
